# Programming Course in Python
# NumPy

NumPy is a powerful library for numerical computing in Python.

It provides support for arrays, matrices, and a wide range of mathematical functions, making it essential for scientific computing and data analysis.

First of all, we need to install the library the following way:

**!pip install numpy**

Once it is installed, we can import it and use in our code

In [10]:
import numpy as np

## Array Creation

Creating arrays is a fundamental part of using NumPy.

Arrays in NumPy can be created in several ways, each suited for different needs and types of data.

We will discuss some of the most common methods for creating arrays in NumPy.

**1. Creating Arrays from Lists**

* np.array() function

In [3]:
# Creating a 1D array
list_1d = [1, 2, 3, 4, 5]
array_1d = np.array(list_1d)
print(array_1d)

# Creating a 2D array
list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_2d = np.array(list_2d)
print(array_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**2. Using Built-in Functions**

* np.zeros()

Creates an array filled with zeros. 

In [4]:
# 1D array of zeros
zeros_1d = np.zeros(5)
print(zeros_1d)

# 2D array of zeros
zeros_2d = np.zeros((3, 3))
print(zeros_2d)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


* np.ones()

Creates an array filled with ones. You can specify the shape of the array.

In [5]:
# 1D array of ones
ones_1d = np.ones(5)
print(ones_1d)

# 2D array of ones
ones_2d = np.ones((3, 3))
print(ones_2d)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


* np.full()

Creates an array filled with a specified value.

In [6]:
# 1D array filled with 7
full_1d = np.full(5, 7)
print(full_1d)

# 2D array filled with 7
full_2d = np.full((3, 3), 7)
print(full_2d)

[7 7 7 7 7]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


* np.arange()

Creates an array with a range of values.

In [7]:
# Array with values from 0 to 9
range_array = np.arange(10)
print(range_array)

# Array with values from 1 to 10 with a step of 2
range_array_step = np.arange(1, 11, 2)
print(range_array_step)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


* np.linspace()

Creates an array with evenly spaced values over a specified interval.

In [8]:
# Array with 5 values evenly spaced between 0 and 1
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


* np.eye()

Creates an identity matrix.

In [9]:
# 3x3 Identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Array Attributes

Understanding the attributes of NumPy arrays is crucial for effective array manipulation and operations.

These attributes provide information about the array's structure, data type, and other properties.

Let's learn some essential array attributes in NumPy.

**1. ndarray.ndim**

This attribute returns the number of dimensions (axes) of the array.

In [11]:
array_1d = np.array([1, 2, 3])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_1d.ndim)
print(array_2d.ndim)

1
2


**2. ndarray.shape**

This attribute returns a tuple representing the dimensions of the array.

For a 2D array, it returns (rows, columns).

In [12]:
array_1d = np.array([1, 2, 3])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_1d.shape)
print(array_2d.shape)

(3,)
(2, 3)


**3. ndarray.size**

This attribute returns the total number of elements in the array.

In [13]:
array_1d = np.array([1, 2, 3])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_1d.size)
print(array_2d.size)

3
6


**4. ndarray.dtype**

This attribute returns the data type of the elements in the array.

In [14]:
array_int = np.array([1, 2, 3])
array_float = np.array([1.0, 2.0, 3.0])
print(array_int.dtype)
print(array_float.dtype)

int64
float64


**5. ndarray.itemsize**

This attribute returns the size (in bytes) of each element in the array.

In [15]:
array_int = np.array([1, 2, 3])
array_float = np.array([1.0, 2.0, 3.0])
print(array_int.itemsize)
print(array_float.itemsize)

8
8


**6. ndarray.nbytes**

This attribute returns the total number of bytes consumed by the elements of the array.

In [16]:
array_int = np.array([1, 2, 3])
array_float = np.array([1.0, 2.0, 3.0])
print(array_int.nbytes) # (3 elements * 8 bytes each)
print(array_float.nbytes)

24
24


**7. ndarray.T**

This attribute returns the transposed array (rows become columns and vice versa).

It is mainly used for 2D arrays.

In [17]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.T)

[[1 4]
 [2 5]
 [3 6]]


## Array Indexing

Array indexing allows us to access and manipulate elements within the array.

NumPy supports a variety of indexing techniques we are going to discuss.

**1. Basic Indexing**

Works similarly to Python lists, allowing us to access individual elements using their indices.

In [18]:
array_1d = np.array([10, 20, 30, 40, 50])
print(array_1d[0])  # Output: 10
print(array_1d[4])  # Output: 50

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d[0, 0])  # Output: 1
print(array_2d[1, 2])  # Output: 6

10
50
1
6


**2. Boolean Indexing**

Boolean indexing allows us to filter elements based on conditions.

For a better understanding let's go through an example

In [20]:
array_1d = np.array([10, 20, 30, 40, 50])
bool_idx = array_1d > 25 # check whether the value is greater than 25
print(array_1d[bool_idx])  # Output: [30 40 50]

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
bool_idx = array_2d > 5 # check whether the value is greater than 5
print(array_2d[bool_idx])  # Output: [6 7 8 9]

[30 40 50]
[6 7 8 9]


**3. Fancy Indexing**

Fancy indexing allows us to access multiple elements using arrays of indices.

In [21]:
array_1d = np.array([10, 20, 30, 40, 50])
indices = [1, 3, 4]
print(array_1d[indices])  # Output: [20 40 50]

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = [0, 1, 2]
col_indices = [2, 1, 0]
print(array_2d[row_indices, col_indices])  # Output: [3 5 7]

[20 40 50]
[3 5 7]


**5. Integer Array Indexing**

Integer array indexing allows us to use arrays of integers to index another array.

In [22]:
array_2d = np.array([[1, 2], [3, 4], [5, 6]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 0, 1])
print(array_2d[row_indices, col_indices])

[2 3 6]


## Array Slicing

Slicing allows you to access parts of an array or manipulate sections of an array efficiently.

**1. Basic Slicing**

Basic slicing in NumPy works similarly to Python lists.

We use the colon (:) operator to specify the start, stop, and step of the slice.

array[start:stop:step]

* start: The index where the slice starts (inclusive).
* stop: The index where the slice ends (exclusive).
* step: The step size or interval between indices.

In [23]:
# 1D array slicing
array_1d = np.array([10, 20, 30, 40, 50])
print(array_1d[1:4])

# 2D array slicing
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d[1:, :2])

[20 30 40]
[[4 5]
 [7 8]]


**2. Omitting Indices**

We can omit the start, stop, or step indices, and NumPy will assume default values:

start = 0, stop = size of the dimension, step = 1.

In [24]:
array_1d = np.array([10, 20, 30, 40, 50])
print(array_1d[:3])   # Output: [10 20 30]
print(array_1d[2:])   # Output: [30 40 50]
print(array_1d[::2])  # Output: [10 30 50]

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d[:, 1])  # Output: [2 5 8] (all rows, second column)
print(array_2d[1, :])  # Output: [4 5 6] (second row, all columns)

[10 20 30]
[30 40 50]
[10 30 50]
[2 5 8]
[4 5 6]


**3. Negative Indexing**

Negative indices count from the end of the array.

This can be useful for accessing the last elements of the array.

In [25]:
array_1d = np.array([10, 20, 30, 40, 50])
print(array_1d[-3:])  # Output: [30 40 50]
print(array_1d[:-2])  # Output: [10 20 30]

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d[-2:, -2:])
# Output:
# [[5 6]
#  [8 9]]

[30 40 50]
[10 20 30]
[[5 6]
 [8 9]]


**4. Multi-dimensional Slicing**

Slicing can be applied to multi-dimensional arrays by specifying slices for each dimension.

In [26]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                     [[7, 8, 9], [10, 11, 12]], 
                     [[13, 14, 15], [16, 17, 18]]])

print(array_3d[:2, 1, :])
# Output:
# [[ 4  5  6]
#  [10 11 12]]

print(array_3d[:, :, 1])
# Output:
# [[ 2  5]
#  [ 8 11]
#  [14 17]]

[[ 4  5  6]
 [10 11 12]]
[[ 2  5]
 [ 8 11]
 [14 17]]


**5. Step Slicing**

You can specify a step to skip elements in the array.

A negative step value can be used to reverse the array.

In [27]:
array_1d = np.array([10, 20, 30, 40, 50])
print(array_1d[::2])   # Output: [10 30 50] (every second element)
print(array_1d[::-1])  # Output: [50 40 30 20 10] (reversed array)

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d[::2, ::2])
# Output:
# [[1 3]
#  [7 9]]

[10 30 50]
[50 40 30 20 10]
[[1 3]
 [7 9]]


## Array Mathematics

NumPy provides a wide range of mathematical operations that can be performed on arrays.

These operations include basic arithmetic, statistical calculations, and more complex mathematical functions.

**1. Basic Arithmetic Operations**

* Addition
* Substraction
* Multiplication
* Division

In [29]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Addition
sum_array = array1 + array2
print(sum_array)  # Output: [5 7 9]

# Subtraction
diff_array = array1 - array2
print(diff_array)  # Output: [-3 -3 -3]

# Multiplication
product_array = array1 * array2
print(product_array)  # Output: [ 4 10 18]

# Division
quotient_array = array1 / array2
print(quotient_array)  # Output: [0.25 0.4  0.5 ]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


**2. Scalar Operations**

We can also perform operations between arrays and scalars, applying the operation to each element of the array.

In [30]:
array = np.array([1, 2, 3])

# Scalar addition
sum_scalar = array + 5
print(sum_scalar)  # Output: [6 7 8]

# Scalar multiplication
product_scalar = array * 2
print(product_scalar)  # Output: [2 4 6]

[6 7 8]
[2 4 6]


**3. Statistical Operations**

NumPy provides a range of statistical functions to compute:
* mean
* median
* standard deviation
* variance
* etc

In [31]:
array = np.array([1, 2, 3, 4, 5])

# Mean
mean_value = np.mean(array)
print(mean_value)  # Output: 3.0

# Median
median_value = np.median(array)
print(median_value)  # Output: 3.0

# Standard Deviation
std_value = np.std(array)
print(std_value)  # Output: 1.4142135623730951

# Variance
var_value = np.var(array)
print(var_value)  # Output: 2.0

3.0
3.0
1.4142135623730951
2.0


**4. Trigonometric Functions**

Such as sine, cosine, and tangent.

In [32]:
angles = np.array([0, np.pi/2, np.pi])

# Sine
sin_values = np.sin(angles)
print(sin_values)  # Output: [0. 1. 0.]

# Cosine
cos_values = np.cos(angles)
print(cos_values)  # Output: [ 1.  0. -1.]

# Tangent
tan_values = np.tan(angles)
print(tan_values)  # Output: [ 0.  1.63312394e+16  0.]

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


**5. Exponential and Logarithmic Functions**

In [33]:
array = np.array([1, 2, 3])

# Exponential
exp_values = np.exp(array)
print(exp_values)  # Output: [ 2.71828183  7.3890561  20.08553692]

# Natural Logarithm
log_values = np.log(array)
print(log_values)  # Output: [0.         0.69314718 1.09861229]

# Logarithm base 10
log10_values = np.log10(array)
print(log10_values)  # Output: [0.         0.30103    0.47712125]

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]


**6. Aggregate Functions**

NumPy provides various aggregate functions that operate along specified axes.

In [34]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Sum
total_sum = np.sum(array)
print(total_sum)  # Output: 21

# Sum along axis 0 (columns)
sum_axis0 = np.sum(array, axis=0)
print(sum_axis0)  # Output: [5 7 9]

# Sum along axis 1 (rows)
sum_axis1 = np.sum(array, axis=1)
print(sum_axis1)  # Output: [ 6 15]

21
[5 7 9]
[ 6 15]


## Aggregation Functions in NumPy

As we touched on the topic of Aggregate Functions, let's discuss it deeply.

Aggregation functions in NumPy are used to compute summary statistics and other aggregate values from arrays.

These functions are crucial for data analysis, providing insights into the data through measures like sums, means, medians, variances, and more.

Here are some common aggregation functions provided by NumPy.

**1. Sum**

In [35]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all elements
total_sum = np.sum(array)
print(total_sum)  # Output: 21

# Sum along axis 0 (columns)
sum_axis0 = np.sum(array, axis=0)
print(sum_axis0)  # Output: [5 7 9]

# Sum along axis 1 (rows)
sum_axis1 = np.sum(array, axis=1)
print(sum_axis1)  # Output: [ 6 15]

21
[5 7 9]
[ 6 15]


**2. Mean**

In [36]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Mean of all elements
mean_value = np.mean(array)
print(mean_value)  # Output: 3.5

# Mean along axis 0 (columns)
mean_axis0 = np.mean(array, axis=0)
print(mean_axis0)  # Output: [2.5 3.5 4.5]

# Mean along axis 1 (rows)
mean_axis1 = np.mean(array, axis=1)
print(mean_axis1)  # Output: [2. 5.]

3.5
[2.5 3.5 4.5]
[2. 5.]


**3. Median**

In [37]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Median of all elements
median_value = np.median(array)
print(median_value)  # Output: 3.5

# Median along axis 0 (columns)
median_axis0 = np.median(array, axis=0)
print(median_axis0)  # Output: [2.5 3.5 4.5]

# Median along axis 1 (rows)
median_axis1 = np.median(array, axis=1)
print(median_axis1)  # Output: [2. 5.]

3.5
[2.5 3.5 4.5]
[2. 5.]


**4. Standard Deviation**

The np.std() function computes the standard deviation of array elements along a specified axis.

In [38]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Standard deviation of all elements
std_value = np.std(array)
print(std_value)  # Output: 1.707825127659933

# Standard deviation along axis 0 (columns)
std_axis0 = np.std(array, axis=0)
print(std_axis0)  # Output: [1.5 1.5 1.5]

# Standard deviation along axis 1 (rows)
std_axis1 = np.std(array, axis=1)
print(std_axis1)  # Output: [0.81649658 0.81649658]

1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


**5. Variance**

The np.var() function computes the variance of array elements along a specified axis.

In [39]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Variance of all elements
var_value = np.var(array)
print(var_value)  # Output: 2.9166666666666665

# Variance along axis 0 (columns)
var_axis0 = np.var(array, axis=0)
print(var_axis0)  # Output: [2.25 2.25 2.25]

# Variance along axis 1 (rows)
var_axis1 = np.var(array, axis=1)
print(var_axis1)  # Output: [0.66666667 0.66666667]

2.9166666666666665
[2.25 2.25 2.25]
[0.66666667 0.66666667]


**6. Minimum and Maximum**

The np.min() and np.max() functions find the minimum and maximum values in the array, respectively.

In [40]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Minimum of all elements
min_value = np.min(array)
print(min_value)  # Output: 1

# Maximum of all elements
max_value = np.max(array)
print(max_value)  # Output: 6

# Minimum along axis 0 (columns)
min_axis0 = np.min(array, axis=0)
print(min_axis0)  # Output: [1 2 3]

# Maximum along axis 1 (rows)
max_axis1 = np.max(array, axis=1)
print(max_axis1)  # Output: [3 6]

1
6
[1 2 3]
[3 6]


**7. Cumulative Sum and Product**

The np.cumsum() and np.cumprod() functions compute the cumulative sum and product of array elements, respectively.

In [41]:
array = np.array([1, 2, 3, 4])

# Cumulative sum
cumsum_values = np.cumsum(array)
print(cumsum_values)  # Output: [ 1  3  6 10]

# Cumulative product
cumprod_values = np.cumprod(array)
print(cumprod_values)  # Output: [ 1  2  6 24]

[ 1  3  6 10]
[ 1  2  6 24]


## Random Number Generation

Random number generation is a crucial aspect of many numerical simulations and data analysis tasks.

NumPy provides a suite of tools for generating random numbers

**1. Generating Random Numbers**

np.random.rand():

Generates random numbers uniformly distributed between 0 and 1.

In [43]:
# Generating a single random number
random_number = np.random.rand()
print(random_number)

# Generating a 1D array of random numbers
random_array_1d = np.random.rand(5)
print(random_array_1d)

# Generating a 2D array of random numbers
random_array_2d = np.random.rand(3, 3)
print(random_array_2d)

0.028898957886691834
[0.76554625 0.3352961  0.96895546 0.92667817 0.90243154]
[[0.23590247 0.17833311 0.19465527]
 [0.26886903 0.12131727 0.77359116]
 [0.86232296 0.4964449  0.41627267]]


np.random.randn():

Generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).

In [44]:
# Generating a single random number from a standard normal distribution
random_normal = np.random.randn()
print(random_normal)

# Generating a 1D array of random numbers from a standard normal distribution
random_normal_array_1d = np.random.randn(5)
print(random_normal_array_1d)

# Generating a 2D array of random numbers from a standard normal distribution
random_normal_array_2d = np.random.randn(3, 3)
print(random_normal_array_2d)

-0.5391431635446554
[-0.91240379 -0.11949198  0.35493903 -0.05815958  0.60679004]
[[ 0.12831733 -0.25024294 -0.49296927]
 [-1.43550115  1.67015089 -0.46080474]
 [ 0.73905627  0.68416025  0.42174981]]


**2. Generating Random Integers**

np.random.randint():

Generates random integers between a specified range.

In [45]:
# Generating a single random integer between 0 and 10
random_int = np.random.randint(0, 10)
print(random_int)

# Generating a 1D array of random integers between 0 and 10
random_int_array_1d = np.random.randint(0, 10, size=5)
print(random_int_array_1d)

# Generating a 2D array of random integers between 0 and 10
random_int_array_2d = np.random.randint(0, 10, size=(3, 3))
print(random_int_array_2d)

8
[8 9 0 2 0]
[[3 9 9]
 [9 3 1]
 [1 1 7]]


**3. Random Choice**

np.random.choice():

Generates a random sample from a given 1D array.

In [46]:
array = np.array([1, 2, 3, 4, 5])

# Generating a single random choice from the array
random_choice = np.random.choice(array)
print(random_choice)

# Generating multiple random choices from the array
random_choices = np.random.choice(array, size=3)
print(random_choices)

# Generating random choices with replacement
random_choices_replace = np.random.choice(array, size=3, replace=True)
print(random_choices_replace)

5
[4 1 2]
[3 1 3]


**4. Setting a Random Seed**

To ensure reproducibility of random number generation, we can set a random seed.

In [49]:
# Setting a random seed
np.random.seed(42)

# Generating random numbers
random_number = np.random.rand()
print(random_number)  # Output will be the same every time we run this code

0.3745401188473625


**5. Permutations and Shuffling**

np.random.permutation():

Generates a permuted range or array.

In [50]:
# Permute a sequence
permuted_array = np.random.permutation(10)
print(permuted_array)

# Permute a given array
array = np.array([1, 2, 3, 4, 5])
permuted_array = np.random.permutation(array)
print(permuted_array)

[3 9 0 8 5 2 1 6 4 7]
[5 4 1 2 3]


np.random.shuffle():
    
Shuffles the contents of a given array in place.

In [51]:
# Shuffling an array
array = np.array([1, 2, 3, 4, 5])
np.random.shuffle(array)
print(array)  # The array is shuffled in place

[1 3 5 2 4]


## Linear Algebra Operations

These operations are essential for scientific computing, data analysis, and machine learning.

They include matrix multiplication, finding determinants, computing eigenvalues and eigenvectors, and solving systems of linear equations.

**1. Matrix Multiplication**

np.dot() and np.matmul():

* np.dot() is used for dot product of two arrays.
* np.matmul() is used for matrix multiplication.

In [52]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication using np.dot()
result_dot = np.dot(A, B)
print(result_dot)

# Matrix multiplication using np.matmul()
result_matmul = np.matmul(A, B)
print(result_matmul)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


**2. Transpose of a Matrix**

np.transpose() or .T attribute:

* np.transpose() function or .T attribute can be used to transpose a matrix.

In [53]:
A = np.array([[1, 2], [3, 4]])

# Transposing using np.transpose()
transpose_A = np.transpose(A)
print(transpose_A)

# Transposing using .T attribute
transpose_A_T = A.T
print(transpose_A_T)

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


**3. Determinant of a Matrix**

np.linalg.det() -computes the determinant of a square matrix.

In [54]:
A = np.array([[1, 2], [3, 4]])
det_A = np.linalg.det(A)
print(det_A)

-2.0000000000000004


**4. Inverse of a Matrix**

np.linalg.inv() - computes the inverse of a square matrix.

In [56]:
A = np.array([[1, 2], [3, 4]])
inv_A = np.linalg.inv(A)
print(inv_A)

[[-2.   1. ]
 [ 1.5 -0.5]]


**5. Eigenvalues and Eigenvectors**

np.linalg.eig() - computes the eigenvalues and right eigenvectors of a square matrix.

In [57]:
A = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


**6. Solving Systems of Linear Equations**

np.linalg.solve() - solves the linear equation Ax = b for x.

In [58]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

# Solving the system of linear equations Ax = b
x = np.linalg.solve(A, b)
print(x)

[2. 3.]


**7. Matrix Norms**

np.linalg.norm() - computes the norm of a matrix or vector.

In [59]:
A = np.array([[1, 2], [3, 4]])

# Frobenius norm (default)
norm_A = np.linalg.norm(A)
print(norm_A)

# L2 norm (vector norm)
vector = np.array([1, 2, 3])
norm_vector = np.linalg.norm(vector)
print(norm_vector)

5.477225575051661
3.7416573867739413


## Reshaping

Reshaping arrays in NumPy is a crucial operation that allows us to change the shape of an array without changing its data.

Syntax:

**numpy.reshape(a, newshape, order='C')**

* a: Array to be reshaped.
* newshape: Desired shape.
* order: Determines whether the array should be flattened row-wise ('C'), column-wise ('F'), or in memory order ('A').

In [60]:
array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = array.reshape((2, 3))
print(reshaped_array)

[[1 2 3]
 [4 5 6]]


**2. Using np.newaxis**

We can use np.newaxis to increase the dimensions of an existing array.

np.newaxis is used to add a new axis to the array, which is useful for adding dimensions to 1D or 2D arrays.

In [61]:
array = np.array([1, 2, 3])
print(array.shape)

# Adding a new axis
array_2d = array[:, np.newaxis]
print(array_2d)
print(array_2d.shape)

(3,)
[[1]
 [2]
 [3]]
(3, 1)


**3. Using np.ravel and np.flatten**

Both ravel and flatten methods are used to flatten a multi-dimensional array into a 1D array.

* np.ravel(): Returns a flattened array. This is a view of the original array whenever possible.
* np.flatten(): Returns a copy of the array collapsed into one dimension.

In [62]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Using ravel
raveled_array = np.ravel(array)
print(raveled_array)  # Output: [1 2 3 4 5 6]

# Using flatten
flattened_array = array.flatten()
print(flattened_array)  # Output: [1 2 3 4 5 6]

[1 2 3 4 5 6]
[1 2 3 4 5 6]


**4. Reshape with order Parameter**

The order parameter in the reshape method specifies the reading and writing order for the elements.

* 'C': Row-major (C-style) order.
* 'F': Column-major (Fortran-style) order.
* 'A': Fortran-style order if the array is Fortran contiguous in memory, C-style otherwise.

In [63]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape in row-major order
reshaped_c = array.reshape((3, 2), order='C')
print(reshaped_c)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]]

# Reshape in column-major order
reshaped_f = array.reshape((3, 2), order='F')
print(reshaped_f)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]

[[1 2]
 [3 4]
 [5 6]]
[[1 5]
 [4 3]
 [2 6]]


**5. np.transpose and np.swapaxes**

* np.transpose(): Permutes the dimensions of the array.
* np.swapaxes(): Interchanges two axes of an array. This is useful for specific transpositions in higher-dimensional arrays.

In [64]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose the array
transposed_array = np.transpose(array)
print(transposed_array)

# Swap axes
swapped_array = np.swapaxes(array, 0, 1)
print(swapped_array)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


## Congratulations!

We've completed learning most important and useful basics in NumPy Library, now you have a solid foundation in one of the most powerful tools for numerical computing in Python.

To consolidate your knowledge you will have to practice your skills on the tasks which would be presented in another file.

*Good Luck!*