# NumPy Answers

Hello everyone!

I hope you trained your skills and ready to check yourself.

Here are the correct codes for your tasks.

Enjoy ;)

In [1]:
import numpy as np

## Task 1

How to tell if a given 2D array has null columns?

In [2]:
# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

False
[False False  True]


## Task 2

Considering two arrays with shape (1,3) and (3,1), how to compute their sum

In [3]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


## Task 3

Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [4]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


## Task 4

Create a null vector of size 10

In [5]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Task 5

Find the nearest value from a given value in an array

In [6]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5050175008009574
